apiVersion: v2
name: k8s-simple-logs
description: A simple Kubernetes log aggregation utility that exposes logs from all pods in the namespace via HTTP
type: application
version: 2025.10.4
appVersion: "2025.10.4"
keywords:
  - logs
  - kubernetes
  - monitoring
home: https://github.com/fredsmith/k8s-simple-logs
sources:
  - https://github.com/fredsmith/k8s-simple-logs
maintainers:
  - name: fredsmith
