apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-simple-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-simple-logs
  template:
    metadata:
      labels:
        app: k8s-simple-logs
    spec:
      serviceAccountName: k8s-simple-logs
      containers:
      - name: k8s-simple-logs
        image: docker.io/derf/k8s-simple-logs:latest
        imagePullPolicy: IfNotPresent
        command: ["/app/k8s-simple-logs"]
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: http
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: http
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 100Mi
