apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml

commonLabels:
  app: k8s-simple-logs
  app.kubernetes.io/name: k8s-simple-logs
  app.kubernetes.io/component: log-aggregator
