apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-simple-logs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-simple-logs
subjects:
- kind: ServiceAccount
  name: k8s-simple-logs
