name: Build and Deploy
on: [ push ]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Container Registry
      uses: docker/login-action@v1
      with:
        registry: hub.docker.com
        username: derf
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate List of Docker Tags
      id: generate-tags
      shell: bash
      run: |
        if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
          echo "##[set-output name=image_tags;] derf/k8s-simple-logs:latest, derf/k8s-simple-logs:${{ github.sha }}";
        else
          echo "##[set-output name=image_tags;] derf/k8s-simple-logs:${{ github.sha }}";
        fi

    - name: Build And Push Image
      id: build-image
      uses: docker/build-push-action@v2
      with:
        tags: ${{ steps.generate-tags.outputs.image_tags }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: Dockerfile
